### Register User API
POST http://localhost:8000/api/users
Content-Type: application/json
Accept: application/json

{
    "username" : "feri",
    "password": "rahasia",
    "name": "Feri Febria Laksana"
}

### Login User API
POST http://localhost:8000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "feri",
    "password": "rahasia"
}

### Get Current User API
GET http://localhost:8000/api/users/current
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

### Update Current User API
PATCH http://localhost:8000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

{
    "name" : "Feri Laksana"
}

### Logout User API
DELETE http://localhost:8000/api/users/logout
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

### Create Contact API
POST http://localhost:8000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

{
    "first_name" : "Feri",
    "last_name" : "Laksana",
    "email" : "feri@mail.com",
    "phone" : "324234324"
}

### GEt Contact API from id #249
GET http://localhost:8000/api/contacts/249
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

### Update Contact API from id #249
PUT http://localhost:8000/api/contacts/249
Accept: application/json
Content-Type: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

{
    "first_name" : "Feri",
    "last_name" : "Febria",
    "email" : "febria@mail.com",
    "phone" : "324234324"
}

### Delete Contact API from id #249
DELETE http://localhost:8000/api/contacts/249
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

### Search Contact API
GET http://localhost:8000/api/contacts?email=joko
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

### Create Address API #250
POST http://localhost:8000/api/contacts/250/addresses
Accept: application/json
Content-Type: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

{
    "street": "jalan belum ada 2",
    "city" : "Yogyakarta",
    "province": "Daerah Istimewa Yogyakarta",
    "country": "indonesia",
    "postal_code": "324234"
}

### Get Address API from AddressId #25
GET http://localhost:8000/api/contacts/250/addresses/25
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

### Update Address API from AddressId #25
PUT http://localhost:8000/api/contacts/250/addresses/25
Accept: application/json
Content-Type: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

{
    "street": "jalan jalan",
    "city" : "Yogyakarta",
    "province": "Daerah Istimewa Yogyakarta",
    "country": "indonesia",
    "postal_code": "324234"
}

### Remove Address API from AddressId #24
DELETE http://localhost:8000/api/contacts/250/addresses/24
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed

### List Address API
GET http://localhost:8000/api/contacts/250/addresses
Accept: application/json
Authorization: e5dc5c97-e03f-4c69-bb82-23a6c95144ed
